### ISSUE TITLE
Dialyzer warnings when calling `use Puid`

### ISSUE THREAD

**Issue by benvp** [puid/Elixir#12]
When calling the `use Puid` I got a dialyzer warning. When adding parameters, the warning count increases to multiple warnings. 

 Any idea what this is?

```elixir
defmodule OneUp.Games.GameId do
  use Puid
end
```

```
The pattern 
          <<_@14:6,_@15:6,_@16:6,_@17:6,_@18:6,_@19:6,_@20:6,_@21:6>> can never match the type 
          <<>>ElixirLS Dialyzer
````

**Comment by dingosky** [comment]
Unable to reproduce. Attached is a screenshot of my copy/paste of your usage.

![elixir-puid-issue-12](https://user-images.githubusercontent.com/134293/199314250-73e70435-bc11-40c0-b806-bef0dfd659f9.jpg)

FWIW, all tests pass was well.

Perhaps a bit of info regarding your environment? Clearly your straightforward usage shouldn't cause issue.

**Comment by benvp** [comment]
Regarding functionality there is no issue. It's just a dialyzer warning popping up - but I am not really sure what it means and  if it's pointing towards something.

**Comment by dingosky** [comment]
Based on the Dialyzer warning you provided (thanks for that as I am still unable to trigger any such warnings) I believe the code in question for the "simple" default usage is in the Puid.Encoding.ASCII module, specifically lines 151-163:

```elixir
            <<s1::@puid_bits_per_char, s2::@puid_bits_per_char, s3::@puid_bits_per_char,
              s4::@puid_bits_per_char, s5::@puid_bits_per_char, s6::@puid_bits_per_char,
              s7::@puid_bits_per_char, s8::@puid_bits_per_char>> ->
              <<
                single_encode(s1)::8,
                single_encode(s2)::8,
                single_encode(s3)::8,
                single_encode(s4)::8,
                single_encode(s5)::8,
                single_encode(s6)::8,
                single_encode(s7)::8,
                single_encode(s8)::8
              >>
```
where with `@puid_bits_per_char=6` (as is the case for the default :safe64 characters) the portion of the bits to be encoded using single encoding clauses is matched for binding to eight 6-bit values. The dialyzer warning (as I read it) indicates this match won't work against `<<>>`, which of course it won't, but the previous lines 148-149:

```elixir
            <<>> ->
              <<>>
```
match that case first, so the dialyzer match in question should never be attempted.  Since the `chunk` function should always return `single_chunk` of either `<<>>` or a bit-size of 8 times the bits per char, one of the above two matches should always happen.

In full disclosure, I'm far shy of Elixir ninja status, so maybe I'm missing an obvious way to trigger the warning(s) you see.

**Comment by 4ndr345** [comment]
Hey @dingosky, I encountered the same problem as well. I spend some time trying to understand it. And I think I have an idea of what the problem is.

My test setup is a standard phoenix app with two additional dependencies:
- `puid`
- `dialyxir`

I added one additional module:
```
defmodule Hello.Password do
  use Puid, chars: :hex
end
```

the output of `mix dialyzer --format raw` is:
```
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@23:4,_@24:4,_@25:4,_@26:4,_@27:4,_@28:4,_@29:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@30:4,_@31:4,_@32:4,_@33:4,_@34:4,_@35:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@36:4,_@37:4,_@38:4,_@39:4,_@40:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@41:4,_@42:4,_@43:4,_@44:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@45:4,_@46:4,_@47:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@48:4,_@49:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@50:4>>', '<<>>']}}
{:warn_matching, {'lib/hello/password.ex', 2}, {:pattern_match, ['pattern <<_@14:4,_@15:4,_@16:4,_@17:4,_@18:4,_@19:4,_@20:4,_@21:4>>', '<<>>']}}
```

With the help of [this post](https://elixirforum.com/t/weird-dialyzer-warning-the-pattern-can-never-match-the-type/33020/11) I was able to look at the code after compilation and macro expansion. 

```-file("lib/hello/password.ex", 2).

-module('Elixir.Hello.Password.Encoding').

-compile([no_auto_import]).

-export(['__info__'/1, encode/1]).

-spec '__info__'(attributes |
                 compile |
                 functions |
                 macros |
                 md5 |
                 exports_md5 |
                 module |
                 deprecated |
                 struct) -> any().

'__info__'(module) -> 'Elixir.Hello.Password.Encoding';
'__info__'(functions) -> [{encode, 1}];
'__info__'(macros) -> [];
'__info__'(struct) -> nil;
'__info__'(exports_md5) ->
    <<"\"\227`\025ZM×*~þÊ¡\024CU ">>;
'__info__'(Key = attributes) ->
    erlang:get_module_info('Elixir.Hello.Password.Encoding',
                           Key);
'__info__'(Key = compile) ->
    erlang:get_module_info('Elixir.Hello.Password.Encoding',
                           Key);
'__info__'(Key = md5) ->
    erlang:get_module_info('Elixir.Hello.Password.Encoding',
                           Key);
'__info__'(deprecated) -> [].

chunk(_@1) -> {_@1, <<>>, <<>>}.

encode(_@1) ->
    {_@2, _@3, _@4} = chunk(_@1),
    _@13 = case _@2 of
               <<>> -> <<>>;
               _ ->
                   << <<(pair_encode(_@5)):16/integer,
                        (pair_encode(_@6)):16/integer,
                        (pair_encode(_@7)):16/integer,
                        (pair_encode(_@8)):16/integer,
                        (pair_encode(_@9)):16/integer,
                        (pair_encode(_@10)):16/integer,
                        (pair_encode(_@11)):16/integer,
                        (pair_encode(_@12)):16/integer>>
                       || <<_@5:8/integer, _@6:8/integer, _@7:8/integer,
                            _@8:8/integer, _@9:8/integer, _@10:8/integer,
                            _@11:8/integer, _@12:8/integer>>
                              <= _@2 >>
           end,
    _@22 = case _@3 of
               <<>> -> <<>>;
               <<_@14:4/integer, _@15:4/integer, _@16:4/integer,
                 _@17:4/integer, _@18:4/integer, _@19:4/integer,
                 _@20:4/integer, _@21:4/integer>> ->
                   <<(single_encode(_@14)):8/integer,
                     (single_encode(_@15)):8/integer,
                     (single_encode(_@16)):8/integer,
                     (single_encode(_@17)):8/integer,
                     (single_encode(_@18)):8/integer,
                     (single_encode(_@19)):8/integer,
                     (single_encode(_@20)):8/integer,
                     (single_encode(_@21)):8/integer>>
           end,
    case _@4 of
        <<_@23:4/integer, _@24:4/integer, _@25:4/integer,
          _@26:4/integer, _@27:4/integer, _@28:4/integer,
          _@29:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@23)):8/integer,
              (single_encode(_@24)):8/integer,
              (single_encode(_@25)):8/integer,
              (single_encode(_@26)):8/integer,
              (single_encode(_@27)):8/integer,
              (single_encode(_@28)):8/integer,
              (single_encode(_@29)):8/integer>>;
        <<_@30:4/integer, _@31:4/integer, _@32:4/integer,
          _@33:4/integer, _@34:4/integer, _@35:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@30)):8/integer,
              (single_encode(_@31)):8/integer,
              (single_encode(_@32)):8/integer,
              (single_encode(_@33)):8/integer,
              (single_encode(_@34)):8/integer,
              (single_encode(_@35)):8/integer>>;
        <<_@36:4/integer, _@37:4/integer, _@38:4/integer,
          _@39:4/integer, _@40:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@36)):8/integer,
              (single_encode(_@37)):8/integer,
              (single_encode(_@38)):8/integer,
              (single_encode(_@39)):8/integer,
              (single_encode(_@40)):8/integer>>;
        <<_@41:4/integer, _@42:4/integer, _@43:4/integer,
          _@44:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@41)):8/integer,
              (single_encode(_@42)):8/integer,
              (single_encode(_@43)):8/integer,
              (single_encode(_@44)):8/integer>>;
        <<_@45:4/integer, _@46:4/integer, _@47:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@45)):8/integer,
              (single_encode(_@46)):8/integer,
              (single_encode(_@47)):8/integer>>;
        <<_@48:4/integer, _@49:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@48)):8/integer,
              (single_encode(_@49)):8/integer>>;
        <<_@50:4/integer>> ->
            <<_@13/binary, _@22/binary,
              (single_encode(_@50)):8/integer>>;
        <<>> -> <<_@13/binary, _@22/binary>>
    end.

...
```

The interesting part is `chunk(_@1) -> {_@1, <<>>, <<>>}.`.  At compile time, it is known that `single_chunk` and ` unchunked` are empty, but the macro generates all cases anyway, which upsets dialyzer.

How can we fix it? I don't know yet. But I'll try to look into it over the holidays.

And also here in full disclosure. I'm by no means an Elixir/macro ninja.

Best Andreas

**Comment by dingosky** [comment]
Thanks Andreas (@4ndr345). Your comment has lead to my being able to reproduce the issue. I can actually do that with a very simple test app. More importantly, thanks for the lead that the issue lies in the macros producing dead code. I'm pondering how best to prevent that.

And of course, any and all input is welcome!

**Comment by dingosky** [comment]
Fixed with commit f95141b589a37fa44c09a197289e050662d07b27. Fortunately this fix does not effect functionality.

@benvp: Pardon the delay in this fix. Regrettably I didn't see the path to reproduce the issue.

@4ndr345: Thanks for showing me that path.

**Comment by benvp** [comment]
No worries, I didn't really understand what happened here and the little warning didn't bother me much. Anyway, the fix is very much appreciated. 👍

**Comment by 4ndr345** [comment]
Hey @dingosky, thanks for your speedy fix. Much appreciated.

**Comment by tomtaylor** [comment]
Hi folks, thanks for looking into this. We're still experiencing it, from what I can tell. We've got `puid` 2.0.4 on Elixir 1.14.0, with `dialyxir` 1.2.0.

```
{:warn_matching, {'lib/poplar/redacted.ex', 2}, {:pattern_match, ['pattern <<<_@2:12,_@3:12,_@4:12,_@5:12,_@6:12,_@7:12,_@8:12,_@9:12,_/binary-unit:1>>, _>', '<<<>>,<<>>>']}}
{:warn_matching, {'lib/poplar/redacted.ex', 2}, {:pattern_match, ['pattern <<<_@2:12,_@3:12,_@4:12,_@5:12,_@6:12,_@7:12,_@8:12,_@9:12,_/binary-unit:1>>, _>', '<<<>>,<<>>>']}}
{:warn_matching, {'lib/poplar/redacted.ex', 6}, {:pattern_match, ['pattern <<<_@2:12,_@3:12,_@4:12,_@5:12,_@6:12,_@7:12,_@8:12,_@9:12,_/binary-unit:1>>, _>', '<<<>>,<<>>>']}}
{:warn_matching, {'lib/poplar/redacted.ex', 2}, {:pattern_match, ['pattern <<<_@2:12,_@3:12,_@4:12,_@5:12,_@6:12,_@7:12,_@8:12,_@9:12,_/binary-unit:1>>, _>', '<<<>>,<<>>>']}}
```

I've redacted the file names above. I've rebuilt the everything, including the PLT from scatch, so I don't think this is a caching issue.

**Comment by dingosky** [comment]
Hi @tomtaylor   Can you specify what `charset` or characters you are using? Will help in my attempts to reproduce. Thx....

**Comment by tomtaylor** [comment]
> Hi @tomtaylor Can you specify what `charset` or characters you are using? Will help in my attempts to reproduce. Thx....

Sure thing - here's an example module. They all have varying `bits`, but all use `alphanum`.

```elixir
defmodule Example.Module do
  use Puid, bits: 64, chars: :alphanum
end
```

**Comment by dingosky** [comment]
Thx. I can reproduce and now can start to wack at the mole.

**Comment by dingosky** [comment]
@tomtaylor, commit aa4187e1a61bd0c23f5121cb958f9a98aabd24c2 (2.0.5) fixes the warnings you were seeing.

In the initial fix for this issue I had overlooked a combination of pairs/single/unchunked encoding chunk sizing.

**Comment by tomtaylor** [comment]
Thanks, that looks like it's done the trick!
